# Patroni 模式测试配置
ssh_user: root
deploy_mode: patroni
build_mode: distribute
pg_source: /Users/zhangqi/Downloads/postgresql-17.9.tar.gz
pg_soft_dir: /usr/local/pgsql
pg_user: postgres
replication_user: replicator
timeout_pg_ready: 60
timeout_basebackup: 300
timeout_scp: 600

# Patroni 组配置
group_0: 0|patroni_test|primary|127.0.0.1:5432:/tmp/pgdata1::::1,127.0.0.1:5433:/tmp/pgdata2::::0
