scope: emashis
namespace: /emashis
name: cn_master
restapi:
  listen: 21.48.241.73:18207
  connect_address: 21.48.241.73:18207
  authentication:
    username: emashis
    password: eMashIS_202602
  allowlist: "21.48.241.73,21.48.241.74,21.48.241.75"
etcd3:
  hosts: 21.48.241.73:22479,21.48.241.74:22479,21.48.241.75:22479
  protocol: https
  cacert: /etc/ssl/etcd-hcpg1/ca.pem
  cert: /etc/ssl/etcd-hcpg1/etcd.pem
  key: /etc/ssl/etcd-hcpg1/etcd-key.pem

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_node_count: 1
    postgresql:
      parameters:
        TimeZone: Asia/Shanghai
        wal_level: replica
        lc_messages: en_US.UTF-8
        lc_monetary: en_US.UTF-8
        lc_numeric: en_US.UTF-8
        lc_time: en_US.UTF-8
        log_checkpoints: 'on'
        log_directory: /log/g000
        log_filename: postgresql-%Y-%m-%d.log
        logging_collector: true
        hot_standby: on
        wal_keep_segments: 200
        max_wal_senders: 20
        max_replication_slots: 20
        wal_log_hints: "on"
        max_slot_wal_keep_size: 32GB
        archive_mode: "on"
        archive_timeout: "0"
        archive_command: "archive_command: /archive/emashis/g001/archive_async.sh qxzx %p %f"
        autovacuum_vacuum_cost_limit: 10000
        restore_command: "/bin/false"
        shared_buffers: "16384MB"
        max_connections: '2000'
        wal_compression: 'lz4'
        shared_preload_libraries: citus
        temp_file_limit: 2048000
      pg_hba:
      - local   all             all                                     trust
      - host    all             all             127.0.0.1/32            trust
      - host    all             all             ::1/128                 trust
      - local   replication     all                                     trust
      - host    replication     all             127.0.0.1/32            trust
      - host    replication     all             ::1/128                 trust
      - host    emas     all             0.0.0.0/0                 md5
      - host    all             patroni_su             21.48.241.0/24            md5
      - host    replication           repluser             21.48.241.0/24            trust
      use_pg_rewind: true
      use_slots: true
  initdb:
    - encoding: "UTF-8"
    - locale: "en_US.UTF-8"
    - wal-segsize: '512'
    - allow-group-access
postgresql:
  listen: 0.0.0.0:15000
  connect_address: 21.48.241.73:15000
  data_dir: /data/cn/db
  bin_dir: /usr/local/pgsql-last/bin
  authentication:
    replication:
      username: repluser
      password: repLusEr_202602
    superuser:
      username: patroni_su
      password: zU6h25X8_wLx_
  callbacks:
    on_start: /etc/pgsql/g001/on-start.sh
tags:
  nofailover: false
  noloadbalance: false
  nosync: false
citus:
  group: 0
  database: emashis
